// <auto-generated />
namespace THN.Web.Cookbook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Concurrency : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Concurrency));
        
        string IMigrationMetadata.Id
        {
            get { return "201703241332598_Concurrency"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
