// <auto-generated />
namespace THN.Web.Cookbook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNoteTypeEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNoteTypeEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201704061642257_AddNoteTypeEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
